FROM ubuntu:latest

MAINTAINER Karabutin Alex <karabutinalex@gmail.com>

RUN mkdir -p /icc
RUN mkdir -p /etc/nginx/sites-enabled

VOLUME ["/project", "/icc", "/etc/nginx/sites-enabled"]

CMD ["true"]
