FROM ubuntu:latest

MAINTAINER Karabutin Alex <karabutinalex@gmail.com>

RUN mkdir -p /icc
RUN mkdir -p /etc/nginx/sites-enabled
RUN mkdir -p /data
RUN mkdir -p /var/lib/postgresql

VOLUME ["/project", "/icc", "/etc/nginx/sites-enabled", "/data", "/var/lib/postgresql"]

CMD ["true"]
